begin;
create temporary table addressed_fixture(label text primary key,id uuid default gen_random_uuid(),invitation uuid);
insert into addressed_fixture(label) values('owner'),('recipient'),('other'),('unverified'),('plan');
grant select,update on addressed_fixture to authenticated;
insert into auth.users(id,email,email_confirmed_at) select id,id||'@example.invalid',case when label='unverified' then null else now() end from addressed_fixture where label<>'plan';
select set_config('request.jwt.claim.sub',(select id::text from addressed_fixture where label='owner'),true);
set local role authenticated;
insert into public.daymark_items(id,title) select id,'Invitation test' from addressed_fixture where label='plan';
select public.daymark_invitation('send',(select id from addressed_fixture where label='plan'),(select id||'@example.invalid' from addressed_fixture where label='recipient'));
reset role;
update addressed_fixture set invitation=(select id from daymark_private.invitations where plan_id=(select id from addressed_fixture where label='plan')) where label='plan';
select set_config('request.jwt.claim.sub',(select id::text from addressed_fixture where label='other'),true);
set local role authenticated;
do $$ begin
 if jsonb_array_length(public.daymark_invitation('list'))<>0 then raise exception 'Other user saw invitation';end if;
 begin perform public.daymark_invitation('accept',p_invitation:=(select invitation from addressed_fixture where label='plan'));raise exception 'Other user accepted';exception when others then if sqlerrm='Other user accepted' then raise;end if;end;
 begin perform public.daymark_invitation_worker('claim');raise exception 'Worker exposed';exception when insufficient_privilege then null;end;
end $$;
reset role;
select set_config('request.jwt.claim.sub',(select id::text from addressed_fixture where label='unverified'),true);
set local role authenticated;
do $$ begin
 begin perform public.daymark_invitation('list');raise exception 'Unverified account allowed';exception when others then if sqlerrm='Unverified account allowed' then raise;end if;end;
end $$;
reset role;
select set_config('request.jwt.claim.sub',(select id::text from addressed_fixture where label='recipient'),true);
set local role authenticated;
do $$ begin
 if jsonb_array_length(public.daymark_invitation('list'))<>1 then raise exception 'Recipient missing invitation';end if;
 if exists(select 1 from public.daymark_items where id=(select id from addressed_fixture where label='plan')) then raise exception 'Access before acceptance';end if;
 perform public.daymark_invitation('accept',p_invitation:=(select invitation from addressed_fixture where label='plan'));
 if not exists(select 1 from public.daymark_items where id=(select id from addressed_fixture where label='plan')) then raise exception 'No access after acceptance';end if;
 if jsonb_array_length(public.daymark_invitation('list'))<>0 then raise exception 'Accepted invitation retained';end if;
end $$;
reset role;
select set_config('request.jwt.claim.sub',(select id::text from addressed_fixture where label='owner'),true);
set local role authenticated;
select public.daymark_share((select id from addressed_fixture where label='plan'),'revoke');
select public.daymark_invitation('send',(select id from addressed_fixture where label='plan'),(select id||'@example.invalid' from addressed_fixture where label='recipient'));
reset role;
update addressed_fixture set invitation=(select id from daymark_private.invitations where plan_id=(select id from addressed_fixture where label='plan')) where label='plan';
select set_config('request.jwt.claim.sub',(select id::text from addressed_fixture where label='recipient'),true);
set local role authenticated;
select public.daymark_invitation('decline',p_invitation:=(select invitation from addressed_fixture where label='plan'));
do $$ begin
 if exists(select 1 from public.daymark_items where id=(select id from addressed_fixture where label='plan')) then raise exception 'Decline granted access';end if;
end $$;
reset role;
select set_config('request.jwt.claim.sub',(select id::text from addressed_fixture where label='owner'),true);
set local role authenticated;
select public.daymark_invitation('send',(select id from addressed_fixture where label='plan'),(select id||'@example.invalid' from addressed_fixture where label='recipient'));
reset role;
update daymark_private.invitations set expires_at=now()-interval '1 minute' where plan_id=(select id from addressed_fixture where label='plan');
select set_config('request.jwt.claim.sub',(select id::text from addressed_fixture where label='recipient'),true);
set local role authenticated;
do $$ begin if jsonb_array_length(public.daymark_invitation('list'))<>0 then raise exception 'Expired invitation shown';end if;end $$;
reset role;
select 'Recipient isolation, acceptance, decline, expiry, verified-account gate and worker isolation passed' as result;
rollback;
