(function(){
  'use strict';
  const STORAGE_KEY='daymark.tasks.v1', THEME_KEY='daymark.theme', ALERTS_KEY='daymark.alerts';
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const els={list:$('#task-list'),empty:$('#empty-state'),form:$('#task-form'),dialog:$('#task-dialog'),confirm:$('#confirm-dialog'),search:$('#search'),priority:$('#priority-filter'),sort:$('#sort'),toast:$('#toast'),scrim:$('#scrim')};
  let filter='all', categoryFilter='', tasks=[], pendingAction=null, undoState=null, toastTimer, alertTimers=new Map();
  const todayISO=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const offsetDate=n=>{const d=new Date();d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const seed=()=>[
    {id:crypto.randomUUID(),title:'Review weekly goals',description:'Choose the three outcomes that matter most this week.',completed:false,priority:'high',category:'Personal',dueDate:todayISO(),dueTime:'18:00',createdAt:new Date(Date.now()-86400000).toISOString(),updatedAt:new Date().toISOString(),completedAt:null},
    {id:crypto.randomUUID(),title:'Prepare project notes',description:'Summarise decisions and next steps for the prototype.',completed:false,priority:'medium',category:'Work',dueDate:offsetDate(2),dueTime:'10:30',createdAt:new Date(Date.now()-50000000).toISOString(),updatedAt:new Date().toISOString(),completedAt:null},
    {id:crypto.randomUUID(),title:'Book a health check',description:'',completed:true,priority:'low',category:'Health',dueDate:offsetDate(-1),dueTime:'',createdAt:new Date(Date.now()-172800000).toISOString(),updatedAt:new Date().toISOString(),completedAt:new Date().toISOString()}
  ];
  function load(){try{const raw=localStorage.getItem(STORAGE_KEY);tasks=raw?JSON.parse(raw):seed();if(!raw)save()}catch(e){tasks=[];announce('Stored tasks could not be loaded. A fresh list has been opened.',true)}}
  function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(tasks))}catch(e){announce('Changes could not be saved on this device.',true)}}
  function alertsEnabled(){return localStorage.getItem(ALERTS_KEY)==='on'&&'Notification'in window&&Notification.permission==='granted'}
  function updateAlertUI(){const supported='Notification'in window,enabled=alertsEnabled(),button=$('#notification-toggle');$('#notification-state').textContent=enabled?'On':'Off';button.querySelector('span:nth-child(2)').textContent=enabled?'Disable alerts':'Enable alerts';button.disabled=!supported;button.title=supported?'Task alerts use this device’s browser notifications.':'Browser notifications are not supported on this device.'}
  function clearAlertTimers(){alertTimers.forEach(clearTimeout);alertTimers.clear()}
  function dueMoment(t){if(!t.dueDate)return null;return new Date(`${t.dueDate}T${t.dueTime||'09:00'}:00`)}
  function notifyTask(t){if(!alertsEnabled()||t.completed||t.notifiedAt)return;try{new Notification('Task due',{body:t.title,tag:`daymark-${t.id}`});t.notifiedAt=new Date().toISOString();save();announce(`Alert sent for “${t.title}”.`)}catch(e){announce('The browser could not display this notification.',true)}}
  function scheduleAlerts(){clearAlertTimers();if(!alertsEnabled())return;const now=Date.now();tasks.filter(t=>!t.completed&&!t.notifiedAt&&t.dueDate).forEach(t=>{const due=dueMoment(t)?.getTime();if(!Number.isFinite(due))return;if(due<=now&&now-due<86400000)notifyTask(t);else if(due>now&&due-now<=2147483647)alertTimers.set(t.id,setTimeout(()=>notifyTask(t),due-now))})}
  const clean=s=>String(s??'').replace(/[<>]/g,'').trim();
  const escapeHTML=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function isOverdue(t){if(t.completed||!t.dueDate)return false;const end=t.dueTime?new Date(`${t.dueDate}T${t.dueTime}`):new Date(`${t.dueDate}T23:59:59`);return end<new Date()}
  function formatDue(t){if(!t.dueDate)return '';const d=new Date(`${t.dueDate}T12:00:00`);let label=t.dueDate===todayISO()?'Today':t.dueDate===offsetDate(1)?'Tomorrow':new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short'}).format(d);return `${label}${t.dueTime?' · '+t.dueTime:''}`}
  function visible(){const q=els.search.value.trim().toLowerCase();let arr=tasks.filter(t=>{const date=t.dueDate||'';const matchesView=filter==='all'||(filter==='today'&&date===todayISO()&&!t.completed)||(filter==='upcoming'&&date>todayISO()&&!t.completed)||(filter==='overdue'&&isOverdue(t))||(filter==='completed'&&t.completed);return matchesView&&(!categoryFilter||t.category===categoryFilter)&&(els.priority.value==='all'||t.priority===els.priority.value)&&(!q||`${t.title} ${t.description}`.toLowerCase().includes(q))});
    const rank={high:0,medium:1,low:2};arr.sort((a,b)=>els.sort.value==='priority'?rank[a.priority]-rank[b.priority]:els.sort.value==='created'?new Date(b.createdAt)-new Date(a.createdAt):els.sort.value==='alpha'?a.title.localeCompare(b.title):(!a.dueDate?1:!b.dueDate?-1:a.dueDate.localeCompare(b.dueDate)||a.dueTime.localeCompare(b.dueTime)));return arr}
  function render(){const arr=visible();els.list.innerHTML=arr.map(t=>`<article class="task-card ${t.completed?'completed':''} ${isOverdue(t)?'overdue':''}" data-id="${t.id}"><input class="check" type="checkbox" ${t.completed?'checked':''} aria-label="Mark ${escapeHTML(t.title)} as ${t.completed?'incomplete':'complete'}"><div><div class="task-title">${escapeHTML(t.title)}</div>${t.description?`<p class="task-description">${escapeHTML(t.description)}</p>`:''}<div class="meta">${t.dueDate?`<span class="chip ${isOverdue(t)?'overdue-chip':''}">${isOverdue(t)?'Overdue · ':''}${escapeHTML(formatDue(t))}</span>`:''}<span class="chip priority-${t.priority}">${t.priority[0].toUpperCase()+t.priority.slice(1)}</span>${t.category?`<span class="chip">${escapeHTML(t.category)}</span>`:''}</div></div><div class="task-menu"><button class="more-btn" aria-label="Actions for ${escapeHTML(t.title)}" aria-expanded="false">⋯</button><div class="menu" hidden><button data-edit>Edit</button><button class="delete" data-delete>Delete</button></div></div></article>`).join('');
    els.empty.hidden=arr.length>0;$('#results-count').textContent=`${arr.length} ${arr.length===1?'task':'tasks'}`;$('#clear-completed').hidden=!tasks.some(t=>t.completed);updateCounts();renderCategories();scheduleAlerts();
  }
  function updateCounts(){const open=tasks.filter(t=>!t.completed).length,done=tasks.length-open,pct=tasks.length?Math.round(done/tasks.length*100):0;$('#count-all').textContent=tasks.length;$('#count-today').textContent=tasks.filter(t=>t.dueDate===todayISO()&&!t.completed).length;$('#count-upcoming').textContent=tasks.filter(t=>t.dueDate>todayISO()&&!t.completed).length;$('#count-overdue').textContent=tasks.filter(isOverdue).length;$('#count-completed').textContent=done;$('#progress-percent').textContent=`${pct}%`;$('#progress-ring').style.setProperty('--p',pct);$('#progress-ring').setAttribute('aria-label',`${pct}% complete`);$('#progress-copy').textContent=tasks.length?`${done} of ${tasks.length} completed · ${open} remaining`:'No tasks yet'}
  function renderCategories(){const cats=[...new Set(tasks.map(t=>t.category).filter(Boolean))].sort();$('#category-nav').innerHTML=cats.map((c,i)=>`<button class="nav-item category-item ${categoryFilter===c?'active':''}" data-category="${escapeHTML(c)}"><span class="category-dot" style="--dot:${['#6c5ce7','#e76f51','#2a9d8f','#e9c46a'][i%4]}"></span>${escapeHTML(c)} <b>${tasks.filter(t=>t.category===c).length}</b></button>`).join('');$('#category-options').innerHTML=cats.map(c=>`<option value="${escapeHTML(c)}">`).join('')}
  function announce(msg,isError=false){const el=$('#status-message');el.textContent=msg;el.style.color=isError?'var(--red)':'';setTimeout(()=>{if(el.textContent===msg)el.textContent=''},3500)}
  function showToast(msg,undo){clearTimeout(toastTimer);$('#toast-message').textContent=msg;$('#undo-btn').hidden=!undo;els.toast.hidden=false;toastTimer=setTimeout(()=>els.toast.hidden=true,5000)}
  function openForm(task){els.form.reset();$('#task-id').value=task?.id||'';$('#dialog-kicker').textContent=task?'EDIT TASK':'NEW TASK';$('#dialog-title').textContent=task?'Edit task':'Add a task';$('#save-task').textContent=task?'Save changes':'Save task';$('#title').value=task?.title||'';$('#description').value=task?.description||'';$('#due-date').value=task?.dueDate||'';$('#due-time').value=task?.dueTime||'';$('#category').value=task?.category||'';(els.form.elements.priority).value=task?.priority||'medium';$('#description-count').textContent=$('#description').value.length;$('#title-error').textContent='';$('#title').classList.remove('invalid');els.dialog.showModal();setTimeout(()=>$('#title').focus(),0)}
  function closeMenus(){$$('.menu').forEach(m=>m.hidden=true);$$('.more-btn').forEach(b=>b.setAttribute('aria-expanded','false'))}
  function confirmAction(title,copy,action,label='Delete'){pendingAction=action;$('#confirm-title').textContent=title;$('#confirm-copy').textContent=copy;$('.danger-btn').textContent=label;els.confirm.showModal()}
  els.form.addEventListener('submit',e=>{e.preventDefault();const title=clean($('#title').value);if(!title){$('#title-error').textContent='Enter a task title.';$('#title').classList.add('invalid');$('#title').focus();return}$('#save-task').disabled=true;const now=new Date().toISOString(),id=$('#task-id').value,old=tasks.find(t=>t.id===id),dueChanged=old&&(old.dueDate!==$('#due-date').value||old.dueTime!==$('#due-time').value);const task={id:id||crypto.randomUUID(),title,description:clean($('#description').value),completed:old?.completed||false,priority:els.form.elements.priority.value,category:clean($('#category').value)||'Uncategorised',dueDate:$('#due-date').value,dueTime:$('#due-time').value,createdAt:old?.createdAt||now,updatedAt:now,completedAt:old?.completedAt||null,notifiedAt:dueChanged?null:(old?.notifiedAt||null)};if(old)tasks=tasks.map(t=>t.id===id?task:t);else tasks.unshift(task);save();render();els.dialog.close();$('#save-task').disabled=false;showToast(old?'Task updated':'Task added',false)});
  els.list.addEventListener('click',e=>{const card=e.target.closest('.task-card');if(!card)return;const id=card.dataset.id,t=tasks.find(x=>x.id===id);if(e.target.matches('.check')){t.completed=e.target.checked;t.completedAt=t.completed?new Date().toISOString():null;t.updatedAt=new Date().toISOString();save();render();showToast(t.completed?'Task completed':'Task reopened',false)}else if(e.target.matches('.more-btn')){const menu=e.target.nextElementSibling,opening=menu.hidden;closeMenus();menu.hidden=!opening;e.target.setAttribute('aria-expanded',String(opening))}else if(e.target.matches('[data-edit]')){closeMenus();openForm(t)}else if(e.target.matches('[data-delete]')){closeMenus();confirmAction('Delete this task?',`“${t.title}” will be permanently removed.`,()=>{const index=tasks.findIndex(x=>x.id===id);undoState={task:t,index};tasks.splice(index,1);save();render();showToast('Task deleted',true)})}});
  els.confirm.addEventListener('close',()=>{if(els.confirm.returnValue==='confirm'&&pendingAction)pendingAction();pendingAction=null});
  $('#undo-btn').addEventListener('click',()=>{if(undoState){tasks.splice(undoState.index,0,undoState.task);undoState=null;save();render();els.toast.hidden=true;announce('Deletion undone.')}});
  $('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;categoryFilter='';$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');const names={all:'All tasks',today:'Today',upcoming:'Upcoming',overdue:'Overdue',completed:'Completed'};$('#view-title').textContent=names[filter];closeSidebar();render()});
  $('#category-nav').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;categoryFilter=b.dataset.category;filter='all';$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#view-title').textContent=categoryFilter;closeSidebar();render()});
  [els.search,els.priority,els.sort].forEach(el=>el.addEventListener(el===els.search?'input':'change',render));
  $('#clear-completed').addEventListener('click',()=>{const n=tasks.filter(t=>t.completed).length;confirmAction('Clear completed tasks?',`${n} completed ${n===1?'task':'tasks'} will be permanently removed.`,()=>{tasks=tasks.filter(t=>!t.completed);save();render();showToast('Completed tasks cleared',false)},'Clear tasks')});
  $('#add-task').addEventListener('click',()=>openForm());$('#empty-add').addEventListener('click',()=>openForm());$$('[data-close]').forEach(b=>b.addEventListener('click',()=>els.dialog.close()));$('#description').addEventListener('input',e=>$('#description-count').textContent=e.target.value.length);$('#title').addEventListener('input',()=>{$('#title-error').textContent='';$('#title').classList.remove('invalid')});
  function closeSidebar(){$('#sidebar').classList.remove('open');els.scrim.classList.remove('visible');els.scrim.hidden=true;$('#menu-btn').setAttribute('aria-expanded','false')}
  $('#menu-btn').addEventListener('click',()=>{const open=!$('#sidebar').classList.contains('open');$('#sidebar').classList.toggle('open',open);els.scrim.hidden=!open;els.scrim.classList.toggle('visible',open);$('#menu-btn').setAttribute('aria-expanded',String(open))});els.scrim.addEventListener('click',closeSidebar);
  function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem(THEME_KEY,theme);$('#theme-toggle span:last-child').textContent=theme==='dark'?'Light theme':'Dark theme';$('#theme-toggle span:first-child').textContent=theme==='dark'?'☀':'☾'}
  $('#theme-toggle').addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));setTheme(localStorage.getItem(THEME_KEY)||((matchMedia('(prefers-color-scheme:dark)').matches)?'dark':'light'));
  $('#notification-toggle').addEventListener('click',async()=>{if(!('Notification'in window)){announce('Browser notifications are not supported on this device.',true);return}if(alertsEnabled()){localStorage.setItem(ALERTS_KEY,'off');clearAlertTimers();updateAlertUI();showToast('Task alerts disabled',false);return}let permission=Notification.permission;if(permission!=='granted')permission=await Notification.requestPermission();if(permission==='granted'){localStorage.setItem(ALERTS_KEY,'on');updateAlertUI();scheduleAlerts();showToast('Task alerts enabled',false)}else{localStorage.setItem(ALERTS_KEY,'off');updateAlertUI();announce('Notifications were not enabled. You can allow them in your browser settings.',true)}});
  $('#date-line').textContent=new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long'}).format(new Date());document.addEventListener('click',e=>{if(!e.target.closest('.task-menu'))closeMenus()});load();updateAlertUI();render();
})();
